# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-12-22 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCentral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguridad_social', models.CharField(blank=True, default='', max_length=25)),
                ('local', models.CharField(blank=True, default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoCentral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_mes', models.CharField(blank=True, default='', max_length=25)),
                ('real_acomulado', models.CharField(blank=True, default='', max_length=25)),
                ('estimado_mes', models.CharField(blank=True, default='', max_length=25)),
                ('estimado_cierre_anno', models.CharField(blank=True, default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_mes', models.CharField(blank=True, default='', max_length=25)),
                ('real_acomulado', models.CharField(blank=True, default='', max_length=25)),
                ('estimado_mes', models.CharField(blank=True, default='', max_length=25)),
                ('estimado_cierre_anno', models.CharField(blank=True, default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('enviado_a', models.DateTimeField(blank=True, null=True)),
                ('actualizado_a_tiempo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='presupuestoglobal',
            name='parte_global',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Provincia', verbose_name='Presupuesto Global'),
        ),
        migrations.AddField(
            model_name='presupuestocentral',
            name='presupuesto_central',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Provincia', verbose_name='Presupuesto Central'),
        ),
        migrations.AddField(
            model_name='localcentral',
            name='local_central',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Provincia', verbose_name='Seguridad Social y Presupuesto Local'),
        ),
    ]
