# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2022-02-02 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListadoProvincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpa', models.CharField(blank=True, max_length=4, null=True)),
                ('nombre', models.CharField(max_length=25)),
                ('actualizado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'listado_provincia',
                'verbose_name_plural': 'listado_provincias',
                'db_table': 'listado_provincia',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoCentral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_real_mes', models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True)),
                ('pc_real_acomulado', models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True)),
                ('pc_estimado_mes', models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True)),
                ('pc_estimado_cierre_anno', models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True)),
            ],
            options={
                'verbose_name': 'presupuesto_central',
                'verbose_name_plural': 'presupuesto_centrales',
                'db_table': 'presupuesto_central',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_real_mes', models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True)),
                ('pg_real_acomulado', models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True)),
                ('pg_estimado_mes', models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True)),
                ('pg_estimado_cierre_anno', models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True)),
            ],
            options={
                'verbose_name': 'presupuesto_global',
                'verbose_name_plural': 'presupuesto_globales',
                'db_table': 'presupuesto_global',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpa', models.CharField(blank=True, max_length=4, null=True)),
                ('nombre', models.CharField(max_length=25)),
                ('enviado_a', models.DateTimeField(blank=True, null=True)),
                ('mes', models.CharField(blank=True, max_length=25, null=True)),
                ('anno', models.CharField(blank=True, max_length=4, null=True)),
                ('enviado_esta_semana', models.BooleanField(default=False)),
                ('presupuesto_central', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PresupuestoCentral', verbose_name='Presupuesto Central')),
                ('presupuesto_global', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PresupuestoGlobal', verbose_name='Presupuesto Global')),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'provincias',
                'db_table': 'provincia',
            },
        ),
    ]
