# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-12-22 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincia',
            name='mes',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
