# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-12-22 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_provincia_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincia',
            name='anno',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
