# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-12-22 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_provincia_anno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocalCentral',
            new_name='SocialCentral',
        ),
    ]
