# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-12-22 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211222_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuestocentral',
            old_name='estimado_cierre_anno',
            new_name='pc_estimado_cierre_anno',
        ),
        migrations.RenameField(
            model_name='presupuestocentral',
            old_name='estimado_mes',
            new_name='pc_estimado_mes',
        ),
        migrations.RenameField(
            model_name='presupuestocentral',
            old_name='real_acomulado',
            new_name='pc_real_acomulado',
        ),
        migrations.RenameField(
            model_name='presupuestocentral',
            old_name='real_mes',
            new_name='pc_real_mes',
        ),
        migrations.RenameField(
            model_name='presupuestoglobal',
            old_name='estimado_cierre_anno',
            new_name='pg_estimado_cierre_anno',
        ),
        migrations.RenameField(
            model_name='presupuestoglobal',
            old_name='estimado_mes',
            new_name='pg_estimado_mes',
        ),
        migrations.RenameField(
            model_name='presupuestoglobal',
            old_name='real_acomulado',
            new_name='pg_real_acomulado',
        ),
        migrations.RenameField(
            model_name='presupuestoglobal',
            old_name='real_mes',
            new_name='pg_real_mes',
        ),
        migrations.RenameField(
            model_name='socialcentral',
            old_name='local',
            new_name='presupuest_local',
        ),
        migrations.RenameField(
            model_name='socialcentral',
            old_name='seguridad_social',
            new_name='presupuest_seguridad_social',
        ),
    ]
