# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-12-24 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211222_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialcentral',
            name='local_central',
        ),
        migrations.AlterModelOptions(
            name='presupuestocentral',
            options={'verbose_name': 'presupuesto_central', 'verbose_name_plural': 'presupuesto_centrales'},
        ),
        migrations.AlterModelOptions(
            name='presupuestoglobal',
            options={'verbose_name': 'presupuesto_global', 'verbose_name_plural': 'presupuesto_globales'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'provincia', 'verbose_name_plural': 'provincias'},
        ),
        migrations.AlterModelTable(
            name='presupuestocentral',
            table='presupuesto_central',
        ),
        migrations.AlterModelTable(
            name='presupuestoglobal',
            table='presupuesto_global',
        ),
        migrations.AlterModelTable(
            name='provincia',
            table='provincia',
        ),
        migrations.DeleteModel(
            name='SocialCentral',
        ),
    ]
