# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-12-24 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211224_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestocentral',
            name='pc_estimado_cierre_anno',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestocentral',
            name='pc_estimado_mes',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestocentral',
            name='pc_real_acomulado',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestocentral',
            name='pc_real_mes',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestoglobal',
            name='pg_estimado_cierre_anno',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestoglobal',
            name='pg_estimado_mes',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestoglobal',
            name='pg_real_acomulado',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestoglobal',
            name='pg_real_mes',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
