# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-12-24 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211224_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestocentral',
            name='presupuesto_central',
        ),
        migrations.RemoveField(
            model_name='presupuestoglobal',
            name='parte_global',
        ),
        migrations.AddField(
            model_name='provincia',
            name='presupuesto_central',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PresupuestoCentral', verbose_name='Presupuesto Central'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='presupuesto_global',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PresupuestoGlobal', verbose_name='Presupuesto Global'),
        ),
    ]
