# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-12-24 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_provincia_dpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provincia',
            old_name='actualizado_a_tiempo',
            new_name='enviado',
        ),
    ]
