# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-12-24 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211224_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provincia',
            old_name='enviado',
            new_name='enviado_esta_semana',
        ),
    ]
