# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-12-24 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211224_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListadoProvincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpa', models.CharField(blank=True, max_length=4, null=True)),
                ('nombre', models.CharField(max_length=25)),
                ('actualizado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'listado_provincia',
                'verbose_name_plural': 'listado_provincias',
                'db_table': 'listado_provincia',
            },
        ),
    ]
