# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2022-01-05 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_listadoprovincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestocentral',
            name='pc_estimado_cierre_anno',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestocentral',
            name='pc_estimado_mes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestocentral',
            name='pc_real_acomulado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestocentral',
            name='pc_real_mes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestoglobal',
            name='pg_estimado_cierre_anno',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestoglobal',
            name='pg_estimado_mes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestoglobal',
            name='pg_real_acomulado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestoglobal',
            name='pg_real_mes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
