# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2022-01-05 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220105_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestocentral',
            name='pc_estimado_cierre_anno',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestocentral',
            name='pc_estimado_mes',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestocentral',
            name='pc_real_acomulado',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestocentral',
            name='pc_real_mes',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestoglobal',
            name='pg_estimado_cierre_anno',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestoglobal',
            name='pg_estimado_mes',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestoglobal',
            name='pg_real_acomulado',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestoglobal',
            name='pg_real_mes',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=25, null=True),
        ),
    ]
